#%RAML 1.0
title: SGST PMPC GITP SAPI
version: 1.0
description: System API to handle the PMPC GITP-MQ operations

uses:
  gitpRequest: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/datatypes-library/1.0.14/datatypes-library.raml
  traitsLib: exchange_modules/69195e0c-f771-4438-a4b2-58237c4947b6/traits-library/1.0.6/traits-library.raml

/purchase-orders:
  displayName: purchase orders
  description: resource is used for accepting the Purchase Orders file from SAP and sending it to EPRO and IPS over GITP
  post:
    is:
      - traitsLib.hasContentType
      - traitsLib.hasResponses
      - traitsLib.hasClientIdEnforcement
    body:
      application/json:
        type: gitpRequest.GITPMessage

/purchase-results:
  displayName: purchase results
  description: resource is used for accepting the Purchase Results file from SAP and sending it to ECITA over GITP
  post:
    is:
      - traitsLib.hasContentType
      - traitsLib.hasResponses
      - traitsLib.hasClientIdEnforcement
    body:
      application/json:
        type: gitpRequest.GITPMessage


/fpl:
  displayName: fpl data
  description: resource is used for accepting the FPL file from SAP and sending it to Sales EDI over GITP
  post:
    is:
      - traitsLib.hasContentType
      - traitsLib.hasResponses
      - traitsLib.hasClientIdEnforcement
    body:
      application/json:
        type: gitpRequest.GITPMessage

/ar-statements:
  displayName: ar statements
  description: resource is used for accepting the AR Statement file from SAP and sending it to CMS over GITP
  post:
    is:
      - traitsLib.hasContentType
      - traitsLib.hasResponses
      - traitsLib.hasClientIdEnforcement
    body:
      application/json:
        type: gitpRequest.GITPMessage